name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan Output
        run: terraform show -no-color tfplan > terraform-plan-output.txt

      - name: Upload Terraform Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform-plan-output.txt

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      # === NEW STEPS BELOW ===

      - name: Clone frontend repo
        run: git clone https://github.com/RohitManna11/3tier_python_todo_app.git

      - name: Sync frontend → S3
        run: |
          aws s3 sync 3tier_python_todo_app/frontend \
            s3://${{ secrets.FRONTEND_BUCKET }} \
            --delete
